# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      ZSDK_VERSION: 0.12.4
      ZZEPHYR_VERSION: v2.6.0
      ZSDK_ARCH: arm
      WGET_ARGS: "-q --show-progress --progress=bar:force:noscroll --no-check-certificate"
      ZEPHYR_SDK_INSTALL_DIR: /opt/toolchains/zephyr-sdk
      
    container: craptech/zephyr-ci:no-toolchain
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      #Install SDK
      - name: Install SDK
        run: |
          wget ${WGET_ARGS} https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v${ZSDK_VERSION}/zephyr-toolchain-${ZSDK_ARCH}-${ZSDK_VERSION}-x86_64-linux-setup.run 
          sh "zephyr-toolchain-${ZSDK_ARCH}-${ZSDK_VERSION}-x86_64-linux-setup.run" --quiet -- -d ${ZEPHYR_SDK_INSTALL_DIR}
          rm "zephyr-toolchain-${ZSDK_ARCH}-${ZSDK_VERSION}-x86_64-linux-setup.run"
          
      - name: West initalize
        run: |
          mkdir west
          cd west
          west init --mr ${ZZEPHYR_VERSION}
          cd zephyr
          west update
          
      - name: Build project
        run: |
          cd west
          west build -b ${ZZEPHYR_BOARD} ../
        env: 
          ZEPHYR_TOOLCHAIN_VARIANT: zephyr
          ZZEPHYR_BOARD: nrf52840dongle_nrf52840
  
      - name: Upload firmware
        uses: actions/upload-artifact@v2
        with:
          name: zephyr-image-${ZZEPHYR_BOARD}
          path: |
            west/build/zephyr/zephyr.bin
            west/build/zephyr/zephyr.hex
